
not_installed<-purrr::discard(all_packages,function(x){x %in% installed.packages()[,1]})
sort(not_installed)

cran_pkgs<-not_installed[not_installed %in% available.packages()[,1]]
openxlsx::write.xlsx(data.frame(cran_pkgs=cran_pkgs),"cran_pkgs.xlsx")
cran_pkgs


all_packages<-c(abind = "abind", alphavantager = "alphavantager", anytime = "anytime", 
                apcluster = "apcluster", arrow = "arrow", askpass = "askpass", 
                assertthat = "assertthat", attachment = "attachment", attempt = "attempt", 
                backports = "backports", base = "base", base64enc = "base64enc", 
                benchmarkme = "benchmarkme", benchmarkmeData = "benchmarkmeData", 
                BH = "BH", billboarder = "billboarder", BiocGenerics = "BiocGenerics", 
                BiocManager = "BiocManager", BiocVersion = "BiocVersion", Biostrings = "Biostrings", 
                bit = "bit", bit64 = "bit64", bitops = "bitops", blob = "blob", 
                Boom = "Boom", BoomSpikeSlab = "BoomSpikeSlab", boot = "boot", 
                brew = "brew", brio = "brio", broom = "broom", broom.helpers = "broom.helpers", 
                bsicons = "bsicons", bslib = "bslib", bsts = "bsts", ca = "ca", 
                cachem = "cachem", callr = "callr", car = "car", carData = "carData", 
                cellranger = "cellranger", checkmate = "checkmate", class = "class", 
                classInt = "classInt", cli = "cli", clipr = "clipr", clock = "clock", 
                cluster = "cluster", codetools = "codetools", collapse = "collapse", 
                colorspace = "colorspace", colourpicker = "colourpicker", commonmark = "commonmark", 
                compiler = "compiler", config = "config", conflicted = "conflicted", 
                ConvCalendar = "ConvCalendar", corrplot = "corrplot", corrr = "corrr", 
                cowplot = "cowplot", cpp11 = "cpp11", crayon = "crayon", credentials = "credentials", 
                crosstalk = "crosstalk", crsmeta = "crsmeta", crul = "crul", 
                curl = "curl", data.table = "data.table", datasets = "datasets", 
                datawizard = "datawizard", DBI = "DBI", dbplot = "dbplot", dbplyr = "dbplyr", 
                deldir = "deldir", dendextend = "dendextend", desc = "desc", 
                devEMF = "devEMF", devtools = "devtools", diagram = "diagram", 
                dichromat = "dichromat", diffobj = "diffobj", digest = "digest", 
                doParallel = "doParallel", dotCall64 = "dotCall64", downlit = "downlit", 
                dplyr = "dplyr", DT = "DT", dtplyr = "dtplyr", e1071 = "e1071", 
                editData = "editData", ellipse = "ellipse", ellipsis = "ellipsis", 
                emmeans = "emmeans", estimability = "estimability", evaluate = "evaluate", 
                extrafont = "extrafont", extrafontdb = "extrafontdb", factoextra = "factoextra", 
                FactoMineR = "FactoMineR", fansi = "fansi", farver = "farver", 
                fastmap = "fastmap", fields = "fields", filelock = "filelock", 
                flashClust = "flashClust", flexdashboard = "flexdashboard", flextable = "flextable", 
                FNN = "FNN", fontawesome = "fontawesome", fontBitstreamVera = "fontBitstreamVera", 
                fontLiberation = "fontLiberation", fontquiver = "fontquiver", 
                forcats = "forcats", foreach = "foreach", forecast = "forecast", 
                foreign = "foreign", forge = "forge", formattable = "formattable", 
                fracdiff = "fracdiff", fresh = "fresh", fs = "fs", furrr = "furrr", 
                future = "future", future.apply = "future.apply", gapminder = "gapminder", 
                gargle = "gargle", gclus = "gclus", gdtools = "gdtools", generics = "generics", 
                GenomeInfoDb = "GenomeInfoDb", GenomeInfoDbData = "GenomeInfoDbData", 
                gert = "gert", gfonts = "gfonts", GGally = "GGally", gganimate = "gganimate", 
                ggcorrplot = "ggcorrplot", ggExtra = "ggExtra", ggforce = "ggforce", 
                ggmap = "ggmap", ggplot2 = "ggplot2", ggpubr = "ggpubr", ggrepel = "ggrepel", 
                ggsci = "ggsci", ggsignif = "ggsignif", ggstats = "ggstats", 
                ggstream = "ggstream", ggthemes = "ggthemes", gh = "gh", gitcreds = "gitcreds", 
                globals = "globals", glue = "glue", goftest = "goftest", golem = "golem", 
                googledrive = "googledrive", googlesheets4 = "googlesheets4", 
                gower = "gower", graphics = "graphics", grDevices = "grDevices", 
                grid = "grid", gridExtra = "gridExtra", gridlayout = "gridlayout", 
                gstat = "gstat", gtable = "gtable", hardhat = "hardhat", haven = "haven", 
                here = "here", highcharter = "highcharter", highr = "highr", 
                hms = "hms", htmltools = "htmltools", htmlwidgets = "htmlwidgets", 
                httpcode = "httpcode", httpuv = "httpuv", httr = "httr", httr2 = "httr2", 
                ids = "ids", igraph = "igraph", ini = "ini", insight = "insight", 
                intervals = "intervals", ipred = "ipred", IRanges = "IRanges", 
                IRdisplay = "IRdisplay", IRkernel = "IRkernel", ISLR2 = "ISLR2", 
                isoband = "isoband", iterators = "iterators", jalcal = "jalcal", 
                janitor = "janitor", jpeg = "jpeg", jqr = "jqr", jquerylib = "jquerylib", 
                jsonlite = "jsonlite", kableExtra = "kableExtra", kebabs = "kebabs", 
                keras = "keras", kernlab = "kernlab", KernSmooth = "KernSmooth", 
                keyring = "keyring", knitr = "knitr", labeling = "labeling", 
                labelled = "labelled", later = "later", lattice = "lattice", 
                lava = "lava", lazyeval = "lazyeval", leaflet = "leaflet", leaflet.providers = "leaflet.providers", 
                leaps = "leaps", LiblineaR = "LiblineaR", lifecycle = "lifecycle", 
                listenv = "listenv", listviewer = "listviewer", lme4 = "lme4", 
                lmtest = "lmtest", lobstr = "lobstr", lpSolve = "lpSolve", lsa = "lsa", 
                lubridate = "lubridate", lwgeom = "lwgeom", magick = "magick", 
                magrittr = "magrittr", mapdata = "mapdata", maps = "maps", maptools = "maptools", 
                markdown = "markdown", MASS = "MASS", Matrix = "Matrix", MatrixModels = "MatrixModels", 
                matrixStats = "matrixStats", memoise = "memoise", methods = "methods", 
                mgcv = "mgcv", mime = "mime", miniUI = "miniUI", minqa = "minqa", 
                misc3d = "misc3d", mnormt = "mnormt", modeldb = "modeldb", modelr = "modelr", 
                mongolite = "mongolite", moonBook = "moonBook", multcompView = "multcompView", 
                munsell = "munsell", mvtnorm = "mvtnorm", nlme = "nlme", nloptr = "nloptr", 
                nnet = "nnet", nortest = "nortest", nptest = "nptest", numDeriv = "numDeriv", 
                nycflights13 = "nycflights13", odbc = "odbc", officer = "officer", 
                openssl = "openssl", openxlsx = "openxlsx", osmdata = "osmdata", 
                pacman = "pacman", padr = "padr", pander = "pander", parallel = "parallel", 
                parallelly = "parallelly", patchwork = "patchwork", pbdZMQ = "pbdZMQ", 
                pbkrtest = "pbkrtest", PerformanceAnalytics = "PerformanceAnalytics", 
                permute = "permute", pillar = "pillar", pkgbuild = "pkgbuild", 
                pkgconfig = "pkgconfig", pkgdown = "pkgdown", pkgload = "pkgload", 
                plogr = "plogr", plotly = "plotly", plotrix = "plotrix", plumber = "plumber", 
                plyr = "plyr", png = "png", polyclip = "polyclip", polynom = "polynom", 
                pool = "pool", praise = "praise", prettyunits = "prettyunits", 
                processx = "processx", prodlim = "prodlim", profvis = "profvis", 
                progress = "progress", progressr = "progressr", PROJ = "PROJ", 
                proj4 = "proj4", promises = "promises", proxy = "proxy", pryr = "pryr", 
                ps = "ps", psych = "psych", purrr = "purrr", qap = "qap", quadprog = "quadprog", 
                Quandl = "Quandl", quantmod = "quantmod", quantreg = "quantreg", 
                R.cache = "R.cache", R.methodsS3 = "R.methodsS3", R.oo = "R.oo", 
                R.utils = "R.utils", r2d3 = "r2d3", R6 = "R6", ragg = "ragg", 
                rappdirs = "rappdirs", rapportools = "rapportools", raster = "raster", 
                rcmdcheck = "rcmdcheck", RColorBrewer = "RColorBrewer", Rcpp = "Rcpp", 
                RcppArmadillo = "RcppArmadillo", RcppEigen = "RcppEigen", RcppRoll = "RcppRoll", 
                RcppTOML = "RcppTOML", RCurl = "RCurl", reactable = "reactable", 
                reactR = "reactR", readr = "readr", readxl = "readxl", recipes = "recipes", 
                registry = "registry", rematch = "rematch", rematch2 = "rematch2", 
                remotes = "remotes", repr = "repr", reprex = "reprex", reproj = "reproj", 
                reshape = "reshape", reshape2 = "reshape2", reticulate = "reticulate", 
                rgeos = "rgeos", RgoogleMaps = "RgoogleMaps", rhandsontable = "rhandsontable", 
                riingo = "riingo", rio = "rio", rJava = "rJava", RJDBC = "RJDBC", 
                rjson = "rjson", RJSONIO = "RJSONIO", rlang = "rlang", rlist = "rlist", 
                rmarkdown = "rmarkdown", rnaturalearth = "rnaturalearth", rnaturalearthhires = "rnaturalearthhires", 
                roxygen2 = "roxygen2", rpart = "rpart", RPostgres = "RPostgres", 
                rprojroot = "rprojroot", rrtable = "rrtable", rsample = "rsample", 
                RSQLite = "RSQLite", rstatix = "rstatix", rstudioapi = "rstudioapi", 
                Rttf2pt1 = "Rttf2pt1", rversions = "rversions", rvest = "rvest", 
                rvg = "rvg", rworldmap = "rworldmap", s2 = "s2", S4Vectors = "S4Vectors", 
                sass = "sass", scales = "scales", scatterplot3d = "scatterplot3d", 
                scatterPlotMatrix = "scatterPlotMatrix", scrypt = "scrypt", selectr = "selectr", 
                seriation = "seriation", sessioninfo = "sessioninfo", sf = "sf", 
                sftime = "sftime", shape = "shape", shiny = "shiny", shinybusy = "shinybusy", 
                shinycssloaders = "shinycssloaders", shinydashboard = "shinydashboard", 
                shinydashboardPlus = "shinydashboardPlus", shinyFeedback = "shinyFeedback", 
                shinyfullscreen = "shinyfullscreen", shinyjs = "shinyjs", shinymanager = "shinymanager", 
                shinythemes = "shinythemes", shinyuieditor = "shinyuieditor", 
                shinyWidgets = "shinyWidgets", showtext = "showtext", showtextdb = "showtextdb", 
                sjlabelled = "sjlabelled", sjmisc = "sjmisc", slider = "slider", 
                snakecase = "snakecase", SnowballC = "SnowballC", sodium = "sodium", 
                sourcetools = "sourcetools", sp = "sp", spacetime = "spacetime", 
                spam = "spam", sparklyr = "sparklyr", sparklyr.nested = "sparklyr.nested", 
                sparr = "sparr", SparseM = "SparseM", spatial = "spatial", spatialEco = "spatialEco", 
                spatstat = "spatstat", spatstat.core = "spatstat.core", spatstat.data = "spatstat.data", 
                spatstat.explore = "spatstat.explore", spatstat.geom = "spatstat.geom", 
                spatstat.linnet = "spatstat.linnet", spatstat.model = "spatstat.model", 
                spatstat.random = "spatstat.random", spatstat.sparse = "spatstat.sparse", 
                spatstat.utils = "spatstat.utils", splines = "splines", SQUAREM = "SQUAREM", 
                stars = "stars", stats = "stats", stats4 = "stats4", STRbook = "STRbook", 
                stringdist = "stringdist", stringi = "stringi", stringr = "stringr", 
                styler = "styler", summarytools = "summarytools", survival = "survival", 
                svglite = "svglite", swagger = "swagger", sys = "sys", sysfonts = "sysfonts", 
                systemfonts = "systemfonts", tcltk = "tcltk", tensor = "tensor", 
                tensorflow = "tensorflow", terra = "terra", testthat = "testthat", 
                textshaping = "textshaping", tfautograph = "tfautograph", tfruns = "tfruns", 
                thematic = "thematic", tibble = "tibble", tidypredict = "tidypredict", 
                tidyquant = "tidyquant", tidyr = "tidyr", tidyselect = "tidyselect", 
                tidyverse = "tidyverse", timechange = "timechange", timeDate = "timeDate", 
                timetk = "timetk", tinytex = "tinytex", tmaptools = "tmaptools", 
                tools = "tools", transformr = "transformr", translations = "translations", 
                triebeard = "triebeard", tseries = "tseries", tsfeatures = "tsfeatures", 
                TSP = "TSP", TTR = "TTR", tweenr = "tweenr", tzdb = "tzdb", units = "units", 
                urca = "urca", urlchecker = "urlchecker", urltools = "urltools", 
                usethis = "usethis", utf8 = "utf8", utils = "utils", uuid = "uuid", 
                vcd = "vcd", vctrs = "vctrs", vegan = "vegan", viridis = "viridis", 
                viridisLite = "viridisLite", vroom = "vroom", waiter = "waiter", 
                waldo = "waldo", warp = "warp", webr = "webr", webshot = "webshot", 
                webutils = "webutils", whisker = "whisker", withr = "withr", 
                wk = "wk", writexl = "writexl", xfun = "xfun", XML = "XML", xml2 = "xml2", 
                xopen = "xopen", xtable = "xtable", xts = "xts", XVector = "XVector", 
                yaml = "yaml", zeallot = "zeallot", zgtools = "zgtools", zip = "zip", 
                zlibbioc = "zlibbioc", zoo = "zoo", ztable = "ztable")
